# Generated by Django 4.0.6 on 2022-07-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='status',
            field=models.BooleanField(choices=[('accept', 'accept'), ('pending', 'pending'), ('approved', 'approved')], default='pending'),
        ),
    ]
