# Generated by Django 4.0.6 on 2022-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_registerform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=20)),
                ('team_description', models.TextField(max_length=200)),
                ('product_description', models.TextField(max_length=200)),
                ('problem_description', models.TextField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(choices=[('pending', 'pending'), ('accept', 'accept'), ('approved', 'approved')], default='pending')),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
