# Generated by Django 4.0.6 on 2022-07-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_applicationform_delete_registerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
