# Generated by Django 4.0.6 on 2022-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_slotbook_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbook',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accept', 'accept'), ('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=10),
        ),
    ]
