# Generated by Django 4.0.6 on 2022-07-22 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_slotbook_active_alter_applicationform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbook',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.applicationform'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved'), ('accept', 'accept')], default='pending', max_length=10),
        ),
    ]
