# Generated by Django 4.0.6 on 2022-07-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_slotbook_application_alter_applicationform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('approved', 'approved'), ('pending', 'pending'), ('accept', 'accept')], default='pending', max_length=10),
        ),
    ]
