# Generated by Django 4.0.6 on 2022-07-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_applicationform_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='downloads'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('accept', 'accept'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
