# Generated by Django 4.0.6 on 2022-07-23 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_alter_applicationform_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='image',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
