# Generated by Django 4.0.6 on 2022-07-24 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_remove_applicationform_image_applicationform_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('approved', 'approved'), ('accept', 'accept')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
