# Generated by Django 4.0.6 on 2022-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_applicationform_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='user',
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('accept', 'accept'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
